/// A personalized learning scenario generated by AI during onboarding.
///
/// [accentColor] — one of: 'primary', 'blue', 'green', 'lavender', 'rose'.
/// Maps to AppColors.primary / accentBlue / accentGreen / accentLavender / accentRose.
class Scenario {
  final String id;
  final String title;
  final String description;
  final String icon; // Lucide icon name
  final String accentColor;

  const Scenario({
    required this.id,
    required this.title,
    required this.description,
    required this.icon,
    required this.accentColor,
  });

  factory Scenario.fromJson(Map<String, dynamic> json) {
    return Scenario(
      id: json['id'] as String,
      title: json['title'] as String,
      description: json['description'] as String,
      icon: json['icon'] as String? ?? 'star',
      accentColor: json['accentColor'] as String? ?? 'primary',
    );
  }
}
