/// A personalized learning scenario generated by AI during onboarding.
///
/// [accentColor] — one of: 'primary', 'blue', 'green', 'lavender', 'rose'.
/// Maps to AppColors.primaryColor / accentBlue / accentGreen / accentLavender / accentRose.
class Scenario {
  final String id;
  final String title;
  final String description;
  final String icon; // Lucide icon name
  final String accentColor;
  final String? imageUrl;
  final int level;
  final bool learned;

  const Scenario({
    required this.id,
    required this.title,
    required this.description,
    required this.icon,
    required this.accentColor,
    this.imageUrl,
    this.level = 1,
    this.learned = false,
  });

  factory Scenario.fromJson(Map<String, dynamic> json) {
    return Scenario(
      id: json['id'] as String,
      title: json['title'] as String,
      description: json['description'] as String,
      icon: json['icon'] as String? ?? 'star',
      accentColor: json['accent_color'] as String? ??
          json['accentColor'] as String? ??
          'primary',
      imageUrl: json['image_url'] as String? ?? json['imageUrl'] as String?,
      level: json['level'] as int? ?? 1,
      learned: json['learned'] as bool? ?? false,
    );
  }
}
