import '../../scenarios/models/scenario_access_tier.dart';
import '../../scenarios/models/scenario_type.dart';

/// A personalized learning scenario generated by AI during onboarding.
///
/// [accentColor] — one of: 'primary', 'blue', 'green', 'lavender', 'rose'.
/// Maps to AppColors.primaryColor / accentBlue / accentGreen / accentLavender / accentRose.
///
/// [accessTier] and [type] are optional — onboarding AI payloads predate the
/// scenarios API v2 contract and may omit them. Defaulting to null keeps the
/// existing gift screen parse path intact.
class Scenario {
  final String id;
  final String title;
  final String description;
  final String icon; // Lucide icon name
  final String accentColor;
  final String? imageUrl;
  final int level;
  final bool learned;
  final ScenarioAccessTier? accessTier;
  final ScenarioType? type;

  const Scenario({
    required this.id,
    required this.title,
    required this.description,
    required this.icon,
    required this.accentColor,
    this.imageUrl,
    this.level = 1,
    this.learned = false,
    this.accessTier,
    this.type,
  });

  factory Scenario.fromJson(Map<String, dynamic> json) {
    final rawAccessTier =
        json['access_tier'] as String? ?? json['accessTier'] as String?;
    final rawType = json['type'] as String?;
    return Scenario(
      id: json['id'] as String,
      title: json['title'] as String,
      description: json['description'] as String,
      icon: json['icon'] as String? ?? 'star',
      accentColor: json['accent_color'] as String? ??
          json['accentColor'] as String? ??
          'primary',
      imageUrl: json['image_url'] as String? ?? json['imageUrl'] as String?,
      level: json['level'] as int? ?? 1,
      learned: json['learned'] as bool? ?? false,
      accessTier:
          rawAccessTier == null ? null : ScenarioAccessTier.fromString(rawAccessTier),
      type: rawType == null ? null : ScenarioType.fromString(rawType),
    );
  }
}
